/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

import leetcode.*;

public class AppTest {
    @Test public void testLongestCommonPrefix() {
        assertEquals("wh", LongestCommonPrefix.run(new String[] {"whose", "what", "wh"} ));
        assertEquals("lo", LongestCommonPrefix.run(new String[] {"loo", "loa", "lob"} ));
        assertEquals("", LongestCommonPrefix.run(new String[] {"a", "", "b"} ));
    }
}
